config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get '/lists', to: 'lists#index'
  # get '/lists/new', to: 'lists#new', as: :new_list
  # post '/lists', to: 'lists#create'
  # get '/lists/:id', to: 'lists#show', as: :list
  # get '/lists/:id/bookmarks/new', to: 'bookmarks#new', as: :new_bookmark
  # post '/lists/:id/bookmarks', to: 'bookmarks#create'
  root to: 'lists#index'
  resources :lists do
    resources :bookmarks, only: [ :new, :create ]
  end

  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  validates_associated :bookmarks
  has_many :movies, through: :bookmarks
  validates_associated :movies
  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @bookmark = Bookmark.new(bookmarks_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    @bookmark.save
    redirect_to list_path(@list)
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy!
    redirect_to lists_path
  end

  private

  def bookmarks_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :find_list, only: [:show]

  def index
    @lists = List.all
  end

  def show; end

  def create
    @list = List.new(lists_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def new
    @list = List.new
  end

  private

  def lists_params
    params.require(:list).permit(:name, :photo)
  end

  def find_list
    @list = List.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/create.html.erb
<h1>Bookmark Create</h1>

app/views/bookmarks/new.html.erb
<div class="container">
  <h1>New Bookmark</h1>
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <a class="navbar-brand" href="/lists">
        <i class="fas fa-film fa-2x"></i>
        <%# <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" /> %>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/lists">My Lists</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/lists/new">New List</a>
          </li>
          <li class="nav-item dropdown">
            <i class="fas fa-user-circle fa-2x"></i>
            <%# <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://kitt.lewagon.com/placeholder/users/ssaunier" /> %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
            </div>
          </li>
        </ul>
      </div>
    </div>

    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://cherwell.org/wp-content/uploads/2016/11/IMG_0243.jpg);">
  <div class="container">
    <h1>Save your <strong>favourite</strong> movies to <strong>watchlists</strong>!</h1>
    <p>Personalised movie guide at your fingertips.</p>
    <%= link_to "Create A List", "/lists/new", class: "btn btn-ghost" %>
    <%# <a class="btn btn-flat" href="#">Apply now</a> %>
  </div>
</div>


<div class="container">
  <h1>My Lists</h1>
  <%# <% @lists.each do |list| %>
    <%# <h4> <%= list.name </h4> %>
    <%# <%= cl_image_tag list.photo.key, height: 300, width: 400, crop: :fill %>
  <%# <% end %>

  <div class="container">
    <div class="row">
      <% @lists.each do |list| %>
      <div class="col-12 col-sm-6">
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key, height: 300, crop: :fill %>')">
          <%= link_to list.name, list_path(list) %>
        </div>
      </div>
      <% end %>
    </div>
  </div>



</div>

app/views/lists/new.html.erb
<div class="banner" id="create-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://static.timesofisrael.com/jewishchronicle/uploads/2020/09/Film.jpg);">
  <div class="container">
    <h1><strong>Create</strong> a <strong>new list</strong></h1>
    <p>Save your favourites to watch later.</p>
    <%# <a class="btn btn-flat" href="#">Apply now</a> %>
  </div>
</div>

<div class="container">
  <h1>Your New List</h1>
  <%= simple_form_for @list do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <div class="btn btn-ghost"><%= f.button :submit %></div>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @list.photo.key, crop: :fill %>')">
  <div class="container">
    <h1><strong><%= @list.name %></strong></h1>
    <%= link_to "Create A Bookmark", new_list_bookmark_path(@list), class: "btn btn-ghost" %>
    <%# <a class="btn btn-flat" href="#">Apply now</a> %>
  </div>
</div>

<div class="container">
  <h2><%= @list.name %></h2>
  <br>
  <% @list.movies.each do |movie| %>
    <%= image_tag movie.poster_url, alt: "Le Wagon", width: 200 %>
    <p><%= movie.title %></p>
    <p><%= movie.overview %></p>
    <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
    <%= link_to 'Delete', bookmark_path(bookmark), method: :delete, data: { confirm: 'Do you really want to?' } %>
  <% end %>
</div>